### ISSUE TITLE
Maybe ignore filenames with trailing tilde

### ISSUE THREAD

**Issue by nancym** [surge-sh/ignore#1]
In default Vim, the backup file is created in the same directory as the file with same name followed by a trailing tilde (~). When I "surged" my very simple index.html web site, index.html~ was also surged. I know I could tell surge to ignore those Vim backup files, but I wonder if you want to add that to the default ignored files. I don't have an opinion either way and am just mentioning this.

Thanks!
n.surge.sh

**Comment by kennethormandy** [comment]
Thanks for opening an issue, I definitely didn’t know about this! What do you think, @sintaxi? Should we add:

```
*.*~
```

**Comment by sintaxi** [comment]
Wow, I had no idea about the trailing tilde. I thought vim uses *.swp files
for that. I think it would make sense to add that to the default list. Good
suggestion.
